import { createLogger } from "../../observability/logger.ts";
import { FallbackRouter } from "../fallback.ts";
import type { FusionRequestContext } from "./types.ts";

const log = createLogger("routing.fusion.image-preprocessor");

/**
 * Image content part in OpenAI format.
 */
interface ImageContentPart {
  type: "image_url";
  image_url: {
    url: string;
    detail?: "auto" | "low" | "high";
  };
}

interface TextContentPart {
  type: "text";
  text: string;
}

type ContentPart = ImageContentPart | TextContentPart | Record<string, unknown>;

/**
 * ImagePreprocessor
 *
 * Layer 0 of the fusion pipeline. Scans incoming messages for image content
 * (image_url parts in OpenAI format), dispatches them to a vision-capable
 * model (kimi-k3) for detailed description, and replaces the raw image
 * data with the generated descriptions so that non-vision subagent models can
 * still work with image context.
 */
export class ImagePreprocessor {
  private readonly fallbackRouter: FallbackRouter;

  /** The model routing used for image description. */
  static readonly IMAGE_DESCRIPTION_MODEL = "kimi-k3";

  constructor() {
    this.fallbackRouter = new FallbackRouter();
  }

  // ── Public API ──────────────────────────────────────────────────────

  /**
   * Process all images in the request context.
   * Mutates ctx.messages in-place — image_url parts are replaced with text
   * descriptions generated by the vision model.
   */
  async process(ctx: FusionRequestContext): Promise<void> {
    const { messages } = ctx;

    // Find all messages containing images
    const imageMessages = this.findImageMessages(messages);
    if (imageMessages.length === 0) {
      log.debug("no images detected in request");
      ctx.hadImages = false;
      return;
    }

    ctx.hadImages = true;

    const totalImages = imageMessages.reduce((sum, entry) => sum + entry.images.length, 0);
    log.info("detected images in request", {
      messageCount: imageMessages.length,
      totalImages,
    });

    // Describe each message's images in sequence (or parallel for multiple images)
    const allDescriptions: string[] = [];
    for (const entry of imageMessages) {
      const descriptions = await this.describeImages(ctx, entry.images, entry.assistantContext);
      this.replaceImagesWithDescriptions(entry.msg, entry.images, descriptions);
      allDescriptions.push(...descriptions);
    }

    ctx.imageDescriptions = allDescriptions;

    log.info("image preprocessing complete", { totalImages });
  }

  /**
   * Count images in a request context without processing them.
   * Useful for streaming status messages before processing.
   */
  // ── Image detection ─────────────────────────────────────────────────

  /**
   * Find all messages that contain image content, along with their position
   * and surrounding text context for better descriptions.
   */
  private findImageMessages(
    messages: unknown[],
  ): Array<{ msg: Record<string, unknown>; images: ImageContentPart[]; assistantContext: string }> {
    const results: Array<{
      msg: Record<string, unknown>;
      images: ImageContentPart[];
      assistantContext: string;
    }> = [];

    for (let i = 0; i < messages.length; i++) {
      const msg = messages[i] as Record<string, unknown>;
      const content = msg["content"];

      if (!Array.isArray(content)) continue;

      const images: ImageContentPart[] = [];
      for (const part of content) {
        const p = part as Record<string, unknown>;
        if (p["type"] === "image_url") {
          images.push(p as unknown as ImageContentPart);
        }
      }

      if (images.length > 0) {
        // Gather context from surrounding messages (previous assistant + user text)
        const assistantContext = this.gatherAssistantContext(messages, i);
        results.push({ msg, images, assistantContext });
      }
    }

    return results;
  }

  /**
   * Gather context from adjacent messages for richer image descriptions.
   */
  private gatherAssistantContext(messages: unknown[], currentIndex: number): string {
    const contextParts: string[] = [];

    // Look back at the previous assistant message if any
    for (let i = currentIndex - 1; i >= Math.max(0, currentIndex - 3); i--) {
      const msg = messages[i] as Record<string, unknown>;
      const role = msg["role"];
      const content = msg["content"];

      if (role === "assistant" && typeof content === "string") {
        contextParts.push(`[Previous assistant reply]: ${content.slice(0, 500)}`);
        break;
      }
    }

    // Extract text parts from this message that accompany the images
    const thisContent = messages[currentIndex] as Record<string, unknown>;
    const contentArr = thisContent["content"];
    if (Array.isArray(contentArr)) {
      for (const part of contentArr) {
        const p = part as Record<string, unknown>;
        if (p["type"] === "text" && typeof p["text"] === "string") {
          contextParts.push(`[User text]: ${p["text"]}`);
        }
      }
    }

    return contextParts.join("\n");
  }

  // ── Image description ───────────────────────────────────────────────

  /**
   * Describe one or more images using the vision model.
   * Returns a description for each image, in order.
   */
  private async describeImages(
    ctx: FusionRequestContext,
    images: ImageContentPart[],
    assistantContext: string,
  ): Promise<string[]> {
    if (images.length === 0) return [];

    // For multiple images, describe them all together in one call
    // so the model can reference relationships between them
    const description = await this.callVisionModel(ctx, images, assistantContext);

    // Split the response into per-image sections if we have multiple images
    if (images.length === 1) {
      return [description];
    }

    // For multiple images, try to split by section markers or return the same
    // comprehensive description for all
    const sections = this.splitByImageSections(description, images.length);
    return sections;
  }

  /**
   * Call the vision-capable model (kimi-k2.7-code) to describe images.
   */
  private async callVisionModel(
    ctx: FusionRequestContext,
    images: ImageContentPart[],
    assistantContext: string,
  ): Promise<string> {
    const imageCount = images.length;
    const prompt = imageCount === 1
      ? `Describe this image in comprehensive detail. Include:
- The overall scene/subject
- Key objects, people, text, or elements visible
- Colors, composition, spatial relationships
- Any text or labels present
- The mood, style, or context

Be thorough and specific — this description will be used by other AI models that cannot see the image directly.`
      : `Here are ${imageCount} images. Please describe EACH IMAGE in comprehensive detail, clearly labeling them as "Image 1:", "Image 2:", etc. For each include:
- The overall scene/subject
- Key objects, people, text, or elements visible
- Colors, composition, spatial relationships
- Any text or labels present
- The mood, style, or context

Be thorough and specific — these descriptions will be used by other AI models that cannot see the images directly.`;

    // Build a message with images for the vision model
    const contentParts: ContentPart[] = [
      {
        type: "text" as const,
        text: assistantContext
          ? `Context from the conversation:\n${assistantContext}\n\n${prompt}`
          : prompt,
      },
      ...images.map((img) => ({
        type: "image_url" as const,
        image_url: { url: img.image_url.url, detail: "high" as const },
      })),
    ];

    const visionMessages: Record<string, unknown>[] = [
      {
        role: "system",
        content: "You are a precise image analyst. Describe images in thorough, objective detail. Focus on factual visual elements and avoid subjective interpretation unless asked.",
      },
      {
        role: "user",
        content: contentParts,
      },
    ];

    log.info("describing images via vision model", {
      model: ImagePreprocessor.IMAGE_DESCRIPTION_MODEL,
      imageCount,
    });

    try {
      const response = await this.fallbackRouter.callWithFallback({
        logicalModel: ImagePreprocessor.IMAGE_DESCRIPTION_MODEL,
        requestData: {
          model: ImagePreprocessor.IMAGE_DESCRIPTION_MODEL,
          messages: visionMessages,
          max_tokens: 4096,
        } as Record<string, unknown>,
        targetProtocol: "openai",
        signal: ctx.signal,
        principal: ctx.principal,
        validateResponse: false,
        skipImageDescription: true,
      });

      const description = this.extractText(response);
      log.info("image description received", {
        model: ImagePreprocessor.IMAGE_DESCRIPTION_MODEL,
        descriptionLength: description.length,
      });

      return description;
    } catch (err) {
      log.error("image description failed", {
        model: ImagePreprocessor.IMAGE_DESCRIPTION_MODEL,
        error: String(err),
      });
      return `[Image description unavailable — vision model call failed: ${err instanceof Error ? err.message : String(err)}]`;
    }
  }

  // ── Message mutation ────────────────────────────────────────────────

  /**
   * Replace image_url content parts in a message with their text descriptions.
   */
  private replaceImagesWithDescriptions(
    msg: Record<string, unknown>,
    images: ImageContentPart[],
    descriptions: string[],
  ): void {
    const content = msg["content"];
    if (!Array.isArray(content)) return;

    const newContent: ContentPart[] = [];
    let imageIndex = 0;

    for (const part of content) {
      const p = part as Record<string, unknown>;
      if (p["type"] === "image_url") {
        // Replace with description text
        const desc = descriptions[imageIndex] ?? "(image description unavailable)";
        const detail = (images[imageIndex]?.image_url?.detail ?? "auto");
        const detailNote = detail !== "auto" ? ` (detail: ${detail})` : "";

        newContent.push({
          type: "text" as const,
          text: `[Image${detailNote} description: ${desc}]`,
        });

        imageIndex++;
      } else {
        // Keep non-image parts as-is
        newContent.push(p as ContentPart);
      }
    }

    msg["content"] = newContent;
  }

  // ── Splitting utilities ──────────────────────────────────────────────

  /**
   * Try to split a multi-image description into per-image sections.
   * Falls back to distributing the whole text evenly.
   */
  private splitByImageSections(description: string, expectedCount: number): string[] {
    // Try splitting by "Image N:" or "Image N" markers
    const sectionPattern = /Image\s+(\d+):?/gi;
    const matches = [...description.matchAll(sectionPattern)];

    if (matches.length >= expectedCount) {
      const sections: string[] = [];
      for (let i = 0; i < matches.length; i++) {
        const startIdx = matches[i].index;
        const endIdx = i + 1 < matches.length ? matches[i + 1].index : description.length;
        sections.push(description.slice(startIdx, endIdx).trim());
      }
      // Pad if fewer sections than expected
      while (sections.length < expectedCount) {
        sections.push(sections[sections.length - 1] ?? description);
      }
      return sections.slice(0, expectedCount);
    }

    // Fallback: split the text roughly evenly
    if (expectedCount <= 1) return [description];
    const sectionLength = Math.ceil(description.length / expectedCount);
    const sections: string[] = [];
    for (let i = 0; i < expectedCount; i++) {
      const start = i * sectionLength;
      const end = Math.min(start + sectionLength, description.length);
      sections.push(description.slice(start, end).trim());
    }
    return sections;
  }

  // ── Response parsing ────────────────────────────────────────────────

  /**
   * Extract text content from a provider response.
   */
  private extractText(response: Record<string, unknown>): string {
    // OpenAI format
    const choices = response["choices"] as Array<Record<string, unknown>> | undefined;
    if (choices && choices.length > 0) {
      const message = choices[0]?.["message"] as Record<string, unknown> | undefined;
      if (message && typeof message["content"] === "string") {
        return message["content"];
      }
    }

    // Anthropic format
    const content = response["content"] as Array<Record<string, unknown>> | undefined;
    if (content && Array.isArray(content)) {
      return content
        .filter((b) => b["type"] === "text")
        .map((b) => String(b["text"] ?? ""))
        .join("\n");
    }

    return JSON.stringify(response);
  }
}
